### PR TITLE
Tks 819 sonar code quality fixes code smells token negotiator examples

### PR DESCRIPTION
**Pull request by BankiLouis**

### CODE REVIEW

**Review by nicktaras — APPROVED** [review]
Smoke test run across all the examples and review across changes done.

**Comment by nicktaras** [comment]
@BankiLouis can you review the conflict between PR merges and I can help re-review and merge this change. 

Thanks

**Comment by nicktaras** [comment]
@BankiLouis can you re-base this and we can merge in.

**Comment by nicktaras** [comment]
@BankiLouis please can you help resolve the conflicts for this to merge. 

Let's plan to move this change in for the 2.6.0 release cycle instead of up and coming 2.5.0 to give more time to test.

**Comment by BankiLouis** [comment]
@nicktaras sure let me fix that, sorry I missed this earlier

**Review by nicktaras — APPROVED** [review]

**Pull request merged**
