### PR TITLE
test: 💍 make e2e could run locally

### PR DESCRIPTION
**Pull request by abcfy2**
This PR will allow e2e could run locally.

What I modified:

- add [webServer](https://playwright.dev/docs/test-webserver) config in `playwright.config.ts`
- add run locally steps in `README.md`

In short, that means we should build artifacts first and run locally with [http-server](https://www.npmjs.com/package/http-server) for testing.

But now it runs failed. Seems the reason is `An error occurred loading tokens`. But I don't why the web request `http://localhost:3002/`. Would you please help ?

image

Related ticket: https://smarttokenlabs.atlassian.net/browse/TKS-28

### CODE REVIEW

**Comment by nicktaras** [comment]
Hi @jeanhwa,

Just saw this PR. Is there anything needed to bring this into the examples staging.

**Comment by jeanhwa** [comment]
Hi @abcfy2,

I think it's all good apart from fixing the error with http://localhost:3002/ when run locally as what we had discussed with Nick.

**Comment by abcfy2** [comment]
So this PR could be merged right ? If yes, @jeanhwa please approve & merge my PR. Thanks.

**Comment by nicktaras** [comment]
> Hi @abcfy2,
> 
> I think it's all good apart from fixing the error with http://localhost:3002/ when run locally as what we had discussed with Nick.

Hi guys, 

I remember the issue, sorry for the delay to help with this. I'll look into this today.

The token config appears to be looking for localhost:8080/ticket-issuer-url-website rather than this address + port below

http://127.0.0.1:8080/ticket-issuer-url-website/

**Comment by nicktaras** [comment]
I'll close this PR for now where this task is out of date with the code base.

**Pull request closed without merging**
