### PR TITLE
re: fix header token count && discount price in demo pages

### PR DESCRIPTION
**Pull request by snowwhitedev**

### CODE REVIEW

**Comment by snowwhitedev** [comment]
This PR is for ticket TKS-601  https://smarttokenlabs.atlassian.net/jira/software/c/projects/TKS/boards/13?modal=detail&selectedIssue=TKS-601&assignee=6295de5db407cc0069ff3164

**Comment by micwallace** [comment]
@snowwhitedev there's quite a few issues in this PR. Did you test it with the latest staging build of TN?

1. Header wallet button never shows wallet address/tokens _(I've got a fix for this)_
2. Mint button is not disabled when tokens have already been minted
3. When wallet is disconnected, token state remains. 

It's also not clear why why useStore - selectedTokens is needed, since it is available from the TokenContextProvider. This is probably the reason for issue #3.

I will play around a bit and see if I can fix the last two issues.

**Comment by micwallace** [comment]
@snowwhitedev I've added some fixes in that should address the above. Please give it a quick test. If it's all good on your end we can merge. Note: Please test this only again the latest staging branch of negotiator:

From token-negotiator project
```
git checkout staging
npm run build
```

Then in examples ecommerce project:
```
npm link ../../token-negotiator-examples
npm run dev
```

**Comment by snowwhitedev** [comment]
> @snowwhitedev there's quite a few issues in this PR. Did you test it with the latest staging build of TN?
> 
> 1. Header wallet button never shows wallet address/tokens _(I've got a fix for this)_
> 2. Mint button is not disabled when tokens have already been minted
> 3. When wallet is disconnected, token state remains.
> 
> It's also not clear why why useStore - selectedTokens is needed, since it is available from the TokenContextProvider. This is probably the reason for issue #3.
> 
> I will play around a bit and see if I can fix the last two issues.

@micwallace  It's not working. Although I connected wallet, connect wallet button does not show user's address and tokens found.
I will try to fix it myself.

**Comment by snowwhitedev** [comment]
@micwallace  could you revert your changes in your last commit?

**Comment by snowwhitedev** [comment]
@micwallace  I checked on my local again, it works perfectly. Nice work. Btw should we wait to see working app in deployed site until TKN 2.3.0 published?
cc: @nicktaras

**Review by micwallace — APPROVED** [review]

**Comment by micwallace** [comment]
@snowwhitedev we can deploy with latest staging snapshot to GH pages :-)

Now everytime something is merged into staging branch on token-negotiator a snapshot package is built and published on github package registry. And it can be used in these examples when deployed.

**Pull request merged**
