### PR TITLE
Oh delay TN load

### PR DESCRIPTION
**Pull request by oleggrib**
TN start delay 3s + delay load styles did the trick and speed increades significantly

image

### CODE REVIEW

**Comment by nicktaras** [comment]
Hi @micwallace, could you help smoke test / look at this PR.

Thanks.

**Comment by snowwhitedev** [comment]
@oleggrib  I tried to test on my local, but it does not work now
2023-03-07_03h25_01

**Comment by oleggrib** [comment]
Hi, @snowwhitedev , I know the reason. I used styles from CDN , but after last updates CDN doesnt store TN CSS files.
We can update flow to save TN CSS file locally. Let me do it.

**Comment by oleggrib** [comment]
@snowwhitedev could you check my update?
fix is not most beautiful, but it works. 
feel free to update code to copy CSS file to /out folder with NEXT.JS build flow if you have quick solution

**Review by snowwhitedev — CHANGES_REQUESTED** [review]
Thanks Oleh.
- Could you resolve conflicts?
- I checked google lighthouse score on my local(windows 10, chrome) but it's not so high as like your screenshot. I also tkn example github pages, too, but it shows pretty higher values.
 Could you check it once again?
 FYI, I am attaching my screenshot.

**Comment by snowwhitedev** [comment]
@oleggrib  I am attaching my screenshot.
2023-03-16_14h08_25

**Comment by oleggrib** [comment]
Hi, @snowwhitedev , conflicts resolved.
you are getting bad results because of live-reload code + your browser extensions
to get max results you have to run ```npm run build && npm run start``` and open page in INCOGNITO WINDOW

**Comment by oleggrib** [comment]
Right, but when you test it for local server then results will be very similar. So we can do our best, but in real life it will add some additional delays.

**Review by snowwhitedev — APPROVED** [review]

**Pull request merged**
