### PR TITLE
Fix/e2e test suite

### PR DESCRIPTION
**Pull request by jeanhwa**
- fix test scripts to work with TN v2.3.0
- update metamask extension to v10.25.0
- update npm packages

### CODE REVIEW

**Review by nicktaras — APPROVED** [review]

**Comment by abcfy2** [comment]
SonarCloud failed may fixed after https://github.com/TokenScript/token-negotiator-examples/pull/177 merged.

**Comment by tcglam** [comment]
@abcfy2 - can we close this PR?

**Comment by abcfy2** [comment]
> @abcfy2 - can we close this PR?

I think this can be merged first. And @jeanhwa , do you have any update about this PR ? If your PR is finished, you can merge it yourself because Nick has been already approved.

**Comment by jeanhwa** [comment]
@abcfy2 this PR is done. sure I can merge this first but we need your help to configure the Sonar to ignore checking for metamask extension folder so that it will not fail in future PR.

cc: @nicktaras @tcglam

**Comment by abcfy2** [comment]
> @abcfy2 this PR is done. sure I can merge this first but we need your help to configure the Sonar to ignore checking for metamask extension folder so that it will not fail in future PR.
> 
> cc: @nicktaras @tcglam

Yes please. I've fixed Sonar lint issue. You can merge it and let me check again.

**Pull request merged**
